### ISSUE TITLE
[Feature Request] custom path for --write-info-json

### ISSUE THREAD

**Issue by DarkMahesvara** [pukkandan/yt-dlp#27]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running yt-dlp version **2021.01.20**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would it be possible to implement custom output path for the json info?

e.g:
`--write-info-json=/path/to/json/`

**Comment by pukkandan** [comment]
This can be implemented, but we need a syntax to specify the path. 

> --write-info-json=/path/to/json/

is not possible since it is not backward compatible. My first thought is something like: `--info-json-path`. But then if I were to extend this functionality to subtitles, thumbnail etc, I will have to create a seperate switch for each. I will think about how to do this and let you know. Suggestions are welcome

**Comment by pukkandan** [comment]
I have created this feature: https://github.com/pukkandan/yt-dlp/tree/temp-dir

Once merged, you can use `-P "home:D:\YTDL" -P "infojson:D:\Json Files"` to download the video to `D:\YTDL` and the infojson to `D:\Json Files`.

The code still needs some more testing and review before it is release ready though
