### ISSUE TITLE
[Feature Request] Add Date Option Patch

### ISSUE THREAD

**Issue by kristofferR** [pukkandan/yt-dlp#43]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.01.29**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

There's a fork of youtube-dl by @kade-robertson with a great date option patch, which allows you to add the time/date when the video was uploaded to the filename:
https://github.com/kade-robertson/youtube-dl

Here's the relevant commit/patch:
https://github.com/ytdl-org/youtube-dl/commit/4d6c8b13eb362fa0dba39d8a647cd9697b79cfd9

It would be great if it could get merged in here. It's very useful.

**Comment by pukkandan** [comment]
The patch given is a temporary measure at best. What if someone else wants this functionality for `release_date` instead? Adding all those extra fields only makes the code bloated and hard to maintain in future. I will see if it is possible to create a general solution for this using the output template itself. Maybe something like `-o %(upload_date|yy-mm-dd)t`

**Comment by pukkandan** [comment]
Proof of concept: https://github.com/pukkandan/yt-dlp/commit/446955817afc85665e2a6ca921e6876cc6b2fad2

Eg:

```
>youtube-dlc https://www.youtube.com/watch?v=N5di3IroHnY -o "duration=%(duration>%H-%M-%S)t, uploaded=%(upload_date>%Y day%j)t" --get-filename
duration=00-13-35, uploaded=2020 day309
```

**Comment by kade-robertson** [comment]
Since I got tagged I figured I would post the pull request I originally made for this feature that was closed for the exact reasons above, it's not a great solution. This properly implemented would be a good thing to get into upstream as well (I'm not sure how diverged yt-dlp is at this point).

https://github.com/ytdl-org/youtube-dl/pull/13752

Note dsttfw's feedback:

> The general idea is to allow something like `%(field[:<field_specific_formatter>])<standard_formatter>`.

**Comment by pukkandan** [comment]
> %(field[:<field_specific_formatter>])<standard_formatter>

Let me see if it is possible to make the date formatting work with the standard formatter

**Comment by pukkandan** [comment]
https://github.com/pukkandan/yt-dlp/commit/abb10ff787abdd7b17957bde6021afdb56f41a76

Now it should be possible to do formats like `%(upload_date>%d).1d`, although I don't understand why anyone would want to do that, considering how flexible `strftime` already is

I also changed it to use just `%()s` rather than `%()t`

**Comment by pukkandan** [comment]
Output templates are complicated and I would appreciate if someone could review the code
