### ISSUE TITLE
[Feature Request] Output Format: Upload Year

### ISSUE THREAD

**Issue by undaunt** [pukkandan/yt-dlp#50]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.01.29**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hey @pukkandan, (I'm sure I'm bugging you with all these requests. If you take donations or something, please throw up a link)

I was wondering if it were possible to create an output format of upload_year in addition to the existing upload_date. The use case here being, for non-playlist content from YouTube or similar, to create date based seasons within Plex or wherever. S2018, S2019, etc. - for example for use with [mjarends' metadata agent](https://bitbucket.org/mjarends/extendedpersonalmedia-agent.bundle).

If there is a preexisting way to simply trim the YYYY format out of upload_date I'm not aware of, happy to do that.

Thanks!

**Comment by pukkandan** [comment]
> I'm sure I'm bugging you with all these requests.

Don't worry, you are not. I only work on features that I find interesting (or is simple enough that I can easily implement it)

> If you take donations or something, please throw up a link

I have never been asked this before. I guess I'll set something up - but don't expect it to come with any benefits

Now, about the actual feature, this has actually been implemented in #45 for the request #43. In the master branch, you can use

    %(upload_date>%Y)s

Since youtube-dl released an update today, I'll make a release as soon as I get it merged

**Comment by pukkandan** [comment]
I realized that if you just want the year, you can do it even without this feature by using:

    %(upload_date).4s

But the same trich cant be used to extract date, month etc

**Comment by undaunt** [comment]
This is great, I'm leveraging the .4s option. Thanks!

And of course, no benefits - just a nice way to contribute for your work. I've seen https://www.buymeacoffee.com/ used or a paypal.me link, etc.
