### ISSUE TITLE
[Question] Shouldn't empty playlist description throw an info message, not a warning?

### ISSUE THREAD

**Issue by werid** [pukkandan/yt-dlp#54]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

yt-dlp throws this warning on some channels/playlists:

```WARNING: There's no playlist description to write.```

compare with video description, it will throw warning if there's no playlist description field to extract with that extractor. 

e.g. SVT extractor shows

```WARNING: There's no description to write.```

youtube got a description field, but it can be empty, and it'll just be an info message

```[info] Writing video description to: FILE```

and the resulting ```.description``` is a 0byte file.

Given that youtube do have a playlist description field, but it can be empty, i feel it should follow the video description behaviour, write an empty file and do not throw a warning. 

My normally quiet script updating channels and playlists suddenly got a lot more loud with this warning.

**Comment by pukkandan** [comment]
From my understanding, the warning should actually show for videos with no description (as opposed to an empty description). I will test it and get back to you

**Comment by werid** [comment]
a video with empty .description: https://www.youtube.com/watch?v=B4fidYEat6Y

**Comment by pukkandan** [comment]
What I mean is:

* If the extractor gets a description, even an empty one, no warning is issued.
* If the extractor has no ability to get the description or was unable to get it, you get the warning. 
* Since most extractors support video descriptions, you rarely see the warning unless something is broken.
* I have implemented playlist description only for youtube. So the warning is now issued for all other extractors. 

Technically, this is consistent with previous behaviour. But I understand that this can get annoying. 

I am not sure how to "fix" this. It's not a good idea to just remove the warning. Then if the youtube description extraction ever breaks, we won't get any warning

**Comment by pukkandan** [comment]
I read the OP again and seems like I might have misunderstood the question 🤦 

I see that when the playlist description is blank for youtube, it issues warning. I'll fix it asap
